### ISSUE TITLE
which is right type for given version

### ISSUE THREAD

**Issue by ghost** [fosskers/rs-versions#12]
i have version of things with a p or v in them like 1.2.3p0 or 0.50.0v1 is Version right type for compare these to find greater or less than? is one version scheme use by certain os pkgs others have date or norm semver

**Comment by fosskers** [comment]
Those would both parse as a `Version`, not a `SemVer`. Although, if you'd like to compare via `SemVer` in these cases, you could do a `str::split_once` and send the first `&str` into `SemVer::new`.
