### ISSUE TITLE
Implement as_str and Deref on Versioning

### ISSUE THREAD

**Issue by russellbanks** [fosskers/rs-versions#18]
While Versioning can be created from a `&str`, there is currently no way to get a `&str` from Versioning. The closest method is `to_string` which uses the result of display to create an owned string. This isn't ideal as it requires an allocation to do so.

Here's an [example](https://docs.rs/url/latest/src/url/lib.rs.html#581-583) from the Url crate which stores the full string in its struct so there's no cost to calling `as_str`.

In addition to this, implementing [Deref](https://doc.rust-lang.org/std/ops/trait.Deref.html) would also be helpful so that a reference to Versioning can be dereferenced into a `&str`:
```rust
let version: &str = &Versioning::from_str("1.2.3").unwrap();
```

**Comment by russellbanks** [comment]
Before migrating to rs-versions, I had a New Type wrapper around String. This had an `as_str` and Deref implementation so if a function took &str I was able to dereference the type with &. I'm not in an environment where allocation must be avoided; it was just something I noted when having to either change those functions to accept Versioning or call `to_string` - the difference being an allocation wouldn't have been needed beforehand if I needed it back in a string type.

**Comment by fosskers** [comment]
In this case I'm going to recommend exactly what you've suggested: simply calling `.to_string()` (which routes through the `Display` impl). Although it does cause an allocation, I think that's better overall than redundantly holding the source string in the version type. After all, the original version type might not have even been parsed from an owned `String`, meaning we'd have to clone there anyway.
