### ISSUE TITLE
Add a proper error type instead of ()

### ISSUE THREAD

**Issue by russellbanks** [fosskers/rs-versions#19]
The error type for `Versioning::from_str` is `()`. This doesn't play well when using [clap](https://crates.io/crates/clap) as if the user provided value produces an error, clap needs to output that error to the user.

Therefore, it would be helpful if the error type for Versioning was meaningful and had a reasoning or if a reasoning is not possible, an error type that merely says `Invalid version` at least. The [thiserror](https://crates.io/crates/thiserror) crate is useful when implementing this.

I currently work around this by creating a New Type wrapper around Versioning:

```rust
use color_eyre::eyre::{eyre, Error, Result};
use derive_more::{Deref, Display};
use serde::{Deserialize, Serialize};
use std::str::FromStr;
use versions::Versioning;

#[derive(
    Clone, Default, Deref, Deserialize, Display, Eq, Ord, PartialEq, PartialOrd, Serialize,
)]
pub struct PackageVersion(Versioning);

impl PackageVersion {
    pub fn new(input: &str) -> Result<PackageVersion> {
        Ok(PackageVersion(
            Versioning::from_str(input).map_err(|_| eyre!("Invalid version"))?,
        ))
    }
}

impl FromStr for PackageVersion {
    type Err = Error;

    fn from_str(input: &str) -> Result<PackageVersion, Error> {
        PackageVersion::new(input)
    }
}

```

**Comment by fosskers** [comment]
I've introduced a proper `Error` enum with a `Display` impl, so you should now be able to use this library with `clap` as you described.
