### ISSUE TITLE
Underscores and leading zeros

### ISSUE THREAD

**Issue by chengyuhui** [fosskers/rs-versions#8]
Currently we are using this library to parse a large (~100k) number of versions from a public database. To simplify things, we ignore any version number that is parsed as `Complex` as they are not reliable enough for our use case. However, we've encountered some problems.

## Underscores
```
>>> rs_versions.parse_version('2.4.2-r1')
Ideal(SemVer { major: 2, minor: 4, patch: 2, pre_rel: Some(Chunks([Chunk([Letters("r"), Digits(1)])])), meta: None })
>>> rs_versions.parse_version('2.4.2_r1')
Complex(Mess { chunks: [Digits(2, "2"), Digits(4, "4"), Digits(2, "2")], next: Some((Underscore, Mess { chunks: [Plain("r1")], next: None })) })
>>> rs_versions.parse_version('2.4.2r1')
General(Version { epoch: None, chunks: Chunks([Chunk([Digits(2)]), Chunk([Digits(4)]), Chunk([Digits(2), Letters("r"), Digits(1)])]), meta: None, release: None })
```

Should `2.4.2_r1` be treated the same as `2.4.2r1`? I don't expect them to be `Ideal`, but should at least be `General`. For now we are simply replacing any `_` to `-` to avoid this.

## Leading zeros
We encountered version numbers like `11.1.07`, `3.5.0082`, and `15.08.00`, which are perfectly normal.

The documentation says that `000.007-1` is parsed as `Complex`, is there any consideration behind that?

All the version numbers being parsed as `Complex` are attached, some of them are totally malformed, others looks parseable.

[complex.zip](https://github.com/fosskers/rs-versions/files/7103656/complex.zip)

**Comment by fosskers** [comment]
Hi there, I'm glad to hear that `versions` is useful for you.

> Should 2.4.2_r1 be treated the same as 2.4.2r1? 

I'm going to say that the former should still be a `Mess`, given the definitions of `Version` and `Mess`. The definitions are as they are specifically to make `Ord`-based comparisons sane. However if you know such versions to be safe/harmless, then replacing the underscores with `-` as you're doing is a decent workaround.

> The documentation says that 000.007-1 is parsed as Complex, is there any consideration behind that?

Yes, these are similarly considered `Mess`es both for parsing and for comparison reasons. In theory a function that converted `000.007-1` into `0.7-1` could be easily written, if that still matches your use case. In the meantime, consider the `Mess::nth` function to do this. You could even construct a `SemVer` in this way (and throw out any `Mess` that couldn't be `nth`'d).

**Comment by fosskers** [comment]
Hi there, any thoughts?

**Comment by chengyuhui** [comment]
I still think that some of the examples here should be parsed as at least `Version`, a single `_` probably should not cause such difference when it comes to parsing.

**Comment by fosskers** [comment]
I'm going to keep `_` as a criteria for `Mess` parsing. `Version`s are things very close to `SemVer` and this allows us to compare them sanely, while with `Mess`es it can be hard to know what the meaning of any of the version sections are when they're separated by strange punctuation.
